apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpg-api
  namespace: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fpg-api
  template:
    metadata:
      labels:
        app: fpg-api
    spec:
      nodeName: fpg-worker
      containers:
        - name: fpg-api
          image: tobygaskell/fpg:testing
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: flask_env
              value: testing
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SQL_USER
            - name: SQL_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SQL_PASS
            - name: SQL_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SQL_HOST
            - name: SQL_DB
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SQL_DB
