apiVersion: batch/v1
kind: CronJob
metadata:
  name: fpg-engine-cron
  namespace: testing
spec:
  schedule: "17 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: fpg-engine
              image: tobygaskell/fpg-engine:testing
              imagePullPolicy: Always
              # args: ["-current-round", "38", "-last-round", "38", "-init-results", "False", "-mode", "log"]
              envFrom:
                - secretRef:
                    name: engine-secrets
          restartPolicy: OnFailure