apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-finances
  namespace: house
spec:
  replicas: 2
  selector:
    matchLabels:
      app: house-finances
  template:
    metadata:
      labels:
        app: house-finances
    spec:
      containers:
        - name: house-finances
          image: tobygaskell/house-finances:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          env:
            - name: sql_user
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: sql_user
            - name: sql_password
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: sql_pass
            - name: sql_host
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: sql_host
            - name: sql_db
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: sql_db